### ISSUE TITLE
CSS poravnanje po sredini

### ISSUE THREAD

**Issue by nikovrdoljak** [dklarin/OWS-projekt#2]
HTML elementi moraju biti simetrično raspoređeni na stranici. Npr. na stranici "programer1", kolone su raspoređene u omjeru 3-5-4, a trebale bi biti npr. 3-6-3. Pogledaj na https://getbootstrap.com/docs/3.3/css/#grid detalje.
U tom slučaju i slika mora biti centrirana. Iskoristi CSS klase img-responsive i center-block: https://getbootstrap.com/docs/3.3/css/#images

**Comment by dklarin** [comment]
Poravnao sam sa 4-4-4, to mi nekako najbolje izgleda
