### ISSUE TITLE
app.logger.info korištenje

### ISSUE THREAD

**Issue by nikovrdoljak** [dklarin/OWS-projekt#3]
Dobro si uključio logiranje akcija, no ne trebaju bi na nekim mjestima. Npr:
app.logger.info("Pozvana stranica programer1.html - Benefiti kodiranja i programiranja")
ne treba jer takve stvari uvijek logira web server. 
No zato su dobre na mjestima gdje logiraš npr. uspješan unos. 
Dodaj ih na mjestima gdje se pojavljuje greška. 
Dodaj na kraj log teksta u zagrade i datum i vrijeme logiranja, jer je to koristan podatak za kasniju dijagnostiku logova.

**Comment by dklarin** [comment]
Dodao sam logiranje pri komentiranju, dodao sam stranice 404 i 500 i tu sam stavio logiranje, također  sam dodao bilježenje u datoteku app.log.
