### ISSUE TITLE
Refaktorirati stranice poslova i serija

### ISSUE THREAD

**Issue by nikovrdoljak** [dklarin/OWS-projekt#5]
Umjesto tri zasebne rute (europa, australia, america), napraviti samo jednu rutu:

@app.route('/jobs/<location>')
def user(location):

i samo jedan template, ne tri. 
Ovako svaku izmjenu kod moraš napraviti na tri mjesta.
Ista stvar i sa serijama; samo jedna ruta i template:
@app.route('/shows/<name>')
def shows(name):

**Comment by dklarin** [comment]
Obavljeno!
